version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: intent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: intent
      LOG_LEVEL: INFO
      WEB_ROOT: /app/static
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/dist:/app/static:ro
volumes:
  postgres-data:
